### ISSUE TITLE
Chat timing

### ISSUE THREAD

**Issue by JohnnySn0w** [JohnnySn0w/CyberStorm#11]
[04.pdf](https://github.com/JohnnySn0w/CyberStorm/files/1876652/04.pdf)

**Comment by JohnnySn0w** [comment]
As always, feel free to comment here or ask questions, github's way of working is easy to use, but only once you know what to do.

**Comment by JohnnySn0w** [comment]
the linux system tool, iptables, should be the most useful/complicated part here.

**Comment by DJSanti** [comment]
I created a pull request with the start of the chat timing program for you guys. Please go check it out and work on it -- just the basics of it, like making sure stuff prints to output and that it connects and stuff.

**Comment by JohnnySn0w** [comment]
current working branch is `issue-11/chat-timing`
